### ISSUE TITLE
no responds and white screen when doing DFU

### ISSUE THREAD

**Issue by 19504643** [NordicSemiconductor/Android-nRF-Connect#126]
**Describe the bug**

**To Reproduce**
1. Go to 'SCANNER'
2. Click on 'CONNECT'
3. Scroll down to 'CLIENT'
4. Click on 'DFU'
5. Select file type (ZIP)
6. Click 'OK'
7. See error: When choosing file.zip, once touching the file, the screen turns white

**Expected behavior**
using DFU to update firmware

**Screenshots**
![nrf_screen](https://user-images.githubusercontent.com/4372492/82173068-a8d70380-98fe-11ea-8100-ac316761e4fb.gif)

**Versions (please complete the following information):**
 - Android version: 6.0.1
 - Phone model [e.g. Sumsung Galax S7 (SM-G930L)]
 - App Version [e.g. 4.24.1]

**Additional context**

**Comment by philips77** [comment]
Hello, did you try a different File Browser app?
In the default document browser, instead of selecting a 3rd party app, enable "Show internal storage" in the top-right menu and then select your phone model in the navigation menu. See photos here: https://stackoverflow.com/questions/48193568/how-to-show-the-internal-storage-option-in-an-actionopendocument-intent-by-def
