### ISSUE TITLE
android System BLE Connect 

### ISSUE THREAD

**Issue by v630140** [NordicSemiconductor/Android-nRF-Connect#159]
Hi guys,

I tried to connect to nRF52832 using the app and it was successful. But when I directly use the BLE in the Android system(android 11) settings to connect to the device, it will not be able to connect. The Android system will show that an app is needed to use this device. Please refer to the picture below for the situation.

![image](https://user-images.githubusercontent.com/96040663/145762702-f4c85803-92b6-46c3-a1d5-27d3f3939ee4.png)

What can I do to connect directly to the Android system without APP? 

Thanks.

**Comment by philips77** [comment]
Some app is always needed, otherwise system doesn't know what to do with the connection and disconnects. Some devices, like HID (Human Interface Device) or Audio are supported natively, meaning that the Bluetooth Settings or the OS supports such profile, for those you don't need additional app, but just because there already is an app. For other profiles, which are not supported like that, you need an app that could hold and manage the connection.

**Comment by v630140** [comment]
Thank you for your answer.
