### ISSUE TITLE
decoding of LEGO manufacturer specific data is incomplete

### ISSUE THREAD

**Issue by dlech** [NordicSemiconductor/Android-nRF-Connect#175]
**Describe the bug**

The LEGO manufacturer specific data is currently only decoded as described in https://lego.github.io/lego-ble-wireless-protocol-docs/index.html#document-2-Advertising

However, there are at least 3 known formats of the LEGO (0x0397) manufacturer-specific advertising data. They can be determined as follows:

1. If the advertising data contains the service UUID 0000162**3** -1212-EFDE-1623-785FEABCD123 (0x07 - incomplete list of 128-bit service uuids), then the format at https://lego.github.io/lego-ble-wireless-protocol-docs/index.html#document-2-Advertising is used.
2. If the advertising data contains the service UUID 0000162**5**-1212-EFDE-1623-785FEABCD123(0x07 - incomplete list of 128-bit service uuids), then the format at https://lego.github.io/lego-ble-wireless-protocol-docs/index.html#the-lego-hub-boot-loader-advertising-packet is used.
3. If the advertising data contains no other data types other than manufacturer-specific, then the data has the format specified at https://github.com/NStrijbosch/RevEng-hub2hub-word-blocks

**To Reproduce**
1. Create a program with the LEGO MINDSTORMS app that does hub-to-hub communication and run it
3. Start scanning with the nRF connect app on Android
4. See that format 1 is used instead of format 3

**Expected behavior**
The app should correctly decode the data.

**Comment by philips77** [comment]
Perhaps it's not ideal, but in the upcoming version you'll be able to switch between the 3 parsers. By default, it will be printed as LEGO (the first parser). Tapping it allow to changing to Bootloader or Hub to Hub parser.
The reason is, that in the manufacturer data parser I don't have access to other advertising records, so I can't easily tell what services does the device advertise with.

Will be released in 4.25.4.
