### ISSUE TITLE
automatic connect in background

### ISSUE THREAD

**Issue by schef** [NordicSemiconductor/Android-nRF-Connect#61]
Hi,
i have Samsung Galaxy S6 with android 6.0.1 model SM-G920F.
I have an issue when i use my aplication and have nrf-connect in background that when i make a connect and disconnect in my aplication, change to nrf-connect i see that it is connected to the same device.

Did you have this kind of issue?

**Comment by philips77** [comment]
Hi,
It's not an issue, it's a feature :1st_place_medal: 
Few things:
1. On some phones GATT Server must be configured and enabled, however generally this feature should work based on ACL_CONNECTED broadcast, not only Gatt Server Callback.
2. You may disable it by switching the Settings->Connectivity->Show incoming connections.
3. If you update nRF Connect to 4.18 or newer, instead of nRF Connect silently connecting, a notification will be shown instead, where you may select: connect and open nRF Connect, connect in background, or don't connect.
4. On Android 8.1+ the background connection is done in 'opportunistic' mode (works like a weak reference), so if your app disconnects, nRF Connects also receives DISCONNECT event. On older platforms it indeed keeps the physical connection despite your app disconnected.
5. The same applies to all apps that use ACL_CONNECTED or GATT server in a similar way (although I'm not aware of any).

**Comment by schef** [comment]
Thank you. This helps!
