### ISSUE TITLE
nRF Connect stays in 'disconnecting' state after rebooting device for DFU

### ISSUE THREAD

**Issue by sjanc** [NordicSemiconductor/Android-nRF-Connect#85]
**Describe the bug**
nRF Connect stays in 'disconnecting' state after rebooting device for DFU. When doing DFU with test+confirm device gets disconnected but application doesn't reconnect to set "confirmed" flag on image.

Device is visible but since app is stuck in 'disconnecting' mode I cannot click 'connect' as only "open tab" is available.  Closing tab and clicking connect results in no new tab being created for that device. App restart is required but then it no longer confirm image and firmware gets reverted on next device reboot.

**Comment by philips77** [comment]
Hi Szymon,
I understand you are using mcumgr for Zephyr, not Nordic DFU. How about opening an issue here: https://github.com/runtimeco/mcumgr-android/issues 
If it's only related to nRF Connect, and works with the sample app, or the app you are working on, could you post logs here?

**Comment by philips77** [comment]
After some investigation, I think this issue was related to this one: https://github.com/NordicSemiconductor/Android-BLE-Library/issues/41.
nRF Connect is compiled on developer branches of all libraries, so may have unintentional issues, but that's a way to test them :)
I've fixed the bug yesterday, pushed changes to mcumgr library (https://github.com/runtimeco/mcumgr-android/pull/34) and will release the nRF Connect after fixing this: https://github.com/NordicSemiconductor/Android-DFU-Library/issues/145 issue.
