### ISSUE TITLE
Automated Write/Notify Acknowledgment

### ISSUE THREAD

**Issue by jamesdpowell** [NordicSemiconductor/Android-nRF-Connect#90]
I'm using a GATT service to recall stored data, the service requires notifications to be enabled and then writing a known 4 byte command initiates the service which returns a 32 byte data field. However to recall the next 32 byte string, the first 4 bytes of the previous notify record acts as the acknowledgement. 
So at the moment this is done by manual entry, the amount of data stored is unknown and if an error happens by a mistype this process would require restarting. 
Is there a macro that will take the "notify" field and re-write the first 4 bytes. This can then be looped to retrieve the continuous string of data.
Regards

**Comment by philips77** [comment]
Hi, by design macros are stupid and only allow static data to be sent. Thanks to that they can be very simply recorded and replayed.
Complex actions, like one you need, would require a lot of logic and creating a scripting language. You need 4 bytes, someone else would need 4 bytes as uint32 incremented by 1, or md5/sha of something else. Possibilities are endless.
For your use case I would recommend modifying nRF Blinky code and customizing it to your needs. Requires a bit of Android knowledge, but gives much more freedom.
